library(argparse)
parser = ArgumentParser(description = "Extract tsv files from refphase output")
parser$add_argument("--refphase_rData",type = "character",help = "path to refphase .RData file")
parser$add_argument("--output_dir",type = "character",help = "output directory")
args = parser$parse_args()
print('Loading refphase results from .RData file')
print(args$refphase_rData)
tmp = load(args$refphase_rData)
refphase_results = get(tmp[1])
phased_segments = as.data.frame(refphase_results$phased_segs)
snps = as.data.frame(refphase_results$phased_snps)
purity_ploidy = refphase_results$sample_data
print('Writing phased segments, snps and purity ploidy to tsv files')
print(args$output_dir)
write.table(phased_segments, file = paste0(args$output_dir, "/phased_segs.tsv"), sep = "\t", row.names = FALSE)
write.table(snps, file = paste0(args$output_dir, "/phased_snps.tsv"), sep = "\t", row.names = FALSE)
write.table(purity_ploidy, file = paste0(args$output_dir, "/purity_ploidy.tsv"), sep = "\t", row.names = FALSE)