name: alpaca
channels:
- conda-forge
- bioconda
- defaults
dependencies:
  - ca-certificates
  - gurobi::gurobi
  - openssl
  - pandas
  - python=3.13.2
  - scipy
  - tqdm
  - r-base
  - bioconductor-genomicranges
  - r-jsonlite
  - r-optparse
