name: alpaca
channels:
  - gurobi
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.13.2
  - scipy
  - ca-certificates
  - openssl
  - pandas
  - tqdm
  - conipher
  - gurobi::gurobi
