"""Integration tests for the alpaca CLI.

Each test invokes ``alpaca run`` via subprocess, writes output to pytest's
``tmp_path``, and compares key CSV files against committed golden files stored
in ``tests/<scenario>/expected/``.

Golden files are regenerated by running::

    pytest tests/test_integration.py --update-golden

Columns that vary across runs (timestamps etc.) are excluded from
comparisons via the ``VOLATILE_COLS`` / ``GUROBI_VOLATILE_COLS`` constants
defined in conftest.py.
"""

import shutil

import pandas as pd
import pytest


from golden_utils import VOLATILE_COLS, assert_csv_matches_golden

TUMOUR_ID = "LTX0000-Tumour1"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_PYOMO_GLPK = ("--solver", "pyomo", "--pyomo_solver", "glpk")
_PYOMO_SCIP = ("--solver", "pyomo", "--pyomo_solver", "scip")
_PYOMO_GUROBI = ("--solver", "pyomo", "--pyomo_solver", "gurobi")


def _golden(repo_root, scenario):
    return repo_root / "tests" / scenario / "expected"


# ---------------------------------------------------------------------------
# Core alpaca run tests
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_correct_input(tmp_path, repo_root, run_alpaca, update_golden):
    input_dir = repo_root / "examples" / "example_cohort" / "input" / TUMOUR_ID
    run_alpaca(
        "run",
        "--input_tumour_directory", str(input_dir),
        "--output_directory", str(tmp_path),
        "--debug",
        *_PYOMO_GLPK,
    )

    golden_dir = _golden(repo_root, "correct_input")
    assert_csv_matches_golden(
        tmp_path / f"ALPACA_output_{TUMOUR_ID}.csv",
        golden_dir / f"ALPACA_output_{TUMOUR_ID}.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )
    assert_csv_matches_golden(
        tmp_path / "cn_change_to_ancestor.csv",
        golden_dir / "cn_change_to_ancestor.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )


@pytest.mark.integration
def test_newick_tree_input(tmp_path, repo_root, run_alpaca, update_golden):
    input_dir = repo_root / "tests" / "newick_tree" / "input" / TUMOUR_ID
    run_alpaca(
        "run",
        "--input_tumour_directory", str(input_dir),
        "--output_directory", str(tmp_path),
        "--debug",
        *_PYOMO_GLPK,
    )

    golden_dir = _golden(repo_root, "newick_tree")
    assert_csv_matches_golden(
        tmp_path / f"ALPACA_output_{TUMOUR_ID}.csv",
        golden_dir / f"ALPACA_output_{TUMOUR_ID}.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )
    assert_csv_matches_golden(
        tmp_path / "cn_change_to_ancestor.csv",
        golden_dir / "cn_change_to_ancestor.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )


@pytest.mark.integration
def test_infeasible_segment(tmp_path, repo_root, run_alpaca, update_golden):
    """The nominated segment is simulated infeasible; the other segment is solved normally."""
    infeasible_segment = "1_762496_28527452"
    input_dir = repo_root / "tests" / "infeasible_segment" / "input" / TUMOUR_ID
    run_alpaca(
        "run",
        "--input_tumour_directory", str(input_dir),
        "--output_directory", str(tmp_path),
        "--debug",
        "--simulate_infeasibility", infeasible_segment,
        "--plot_output_mode", "none",
        *_PYOMO_SCIP,
    )

    output_csv = tmp_path / f"ALPACA_output_{TUMOUR_ID}.csv"
    assert output_csv.exists()

    df = pd.read_csv(output_csv)
    assert infeasible_segment not in df["segment"].values, (
        f"Segment {infeasible_segment!r} was simulated infeasible "
        "but appeared in the output."
    )

    golden_dir = _golden(repo_root, "infeasible_segment")
    assert_csv_matches_golden(
        output_csv,
        golden_dir / f"ALPACA_output_{TUMOUR_ID}.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )


@pytest.mark.integration
def test_find_monoclonal_samples(tmp_path, repo_root, run_alpaca, update_golden):
    input_dir = repo_root / "tests" / "find_monoclonal_samples" / "input" / TUMOUR_ID
    run_alpaca(
        "run",
        "--input_tumour_directory", str(input_dir),
        "--output_directory", str(tmp_path),
        "--debug",
        *_PYOMO_GLPK,
    )

    golden_dir = _golden(repo_root, "find_monoclonal_samples")
    assert_csv_matches_golden(
        tmp_path / f"ALPACA_output_{TUMOUR_ID}.csv",
        golden_dir / f"ALPACA_output_{TUMOUR_ID}.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )
    # Post-run cleanup moves all reports into logs_and_reports/
    monoclonal_report = tmp_path / "logs_and_reports" / "monoclonal_samples_report.csv"
    assert monoclonal_report.exists(), "Expected logs_and_reports/monoclonal_samples_report.csv to be produced."
    assert_csv_matches_golden(
        monoclonal_report,
        golden_dir / "monoclonal_samples_report.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )


@pytest.mark.integration
def test_redundant_columns(tmp_path, repo_root, run_alpaca, update_golden):
    input_dir = repo_root / "tests" / "redundant_columns" / "input" / TUMOUR_ID
    run_alpaca(
        "run",
        "--input_tumour_directory", str(input_dir),
        "--output_directory", str(tmp_path),
        *_PYOMO_GLPK,
    )

    golden_dir = _golden(repo_root, "redundant_columns")
    assert_csv_matches_golden(
        tmp_path / f"ALPACA_output_{TUMOUR_ID}.csv",
        golden_dir / f"ALPACA_output_{TUMOUR_ID}.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )


@pytest.mark.integration
def test_sample_name_mismatch(tmp_path, repo_root, run_alpaca):
    """alpaca must exit non-zero when sample names are inconsistent across input tables."""
    input_dir = repo_root / "tests" / "sample_name_mismatch" / "input" / TUMOUR_ID
    result = run_alpaca(
        "run",
        "--input_tumour_directory", str(input_dir),
        "--output_directory", str(tmp_path),
        expect_failure=True,
    )
    assert result.returncode != 0, (
        "Expected alpaca to fail on mismatched sample names but it exited 0."
    )


@pytest.mark.integration
def test_output_all_solutions(tmp_path, repo_root, run_alpaca, update_golden):
    input_dir = repo_root / "examples" / "example_cohort" / "input" / TUMOUR_ID
    run_alpaca(
        "run",
        "--input_tumour_directory", str(input_dir),
        "--output_directory", str(tmp_path),
        "--output_all_solutions",
        "--extra_columns", "gurobi_time", "complexity", "gurobi_gap",
        "--debug",
        *_PYOMO_GLPK,
    )

    golden_dir = _golden(repo_root, "all_solutions")
    assert_csv_matches_golden(
        tmp_path / f"ALPACA_output_{TUMOUR_ID}.csv",
        golden_dir / f"ALPACA_output_{TUMOUR_ID}.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )

    all_solutions_dir = tmp_path / "all_solutions"
    assert all_solutions_dir.is_dir(), "all_solutions/ directory was not created."
    for csv in all_solutions_dir.glob("*.csv"):
        assert_csv_matches_golden(
            csv,
            golden_dir / "all_solutions" / csv.name,
            ignore_cols=VOLATILE_COLS,
            update=update_golden,
        )


@pytest.mark.integration
@pytest.mark.requires_gurobi
def test_solution_provided(tmp_path, repo_root, run_alpaca, update_golden):
    """Test running with a pre-provided solution file (debug mode)."""
    input_dir = repo_root / "tests" / "solution_provided" / "input" / TUMOUR_ID
    debug_solution = input_dir / "tetraploid_solution.csv"
    run_alpaca(
        "run",
        "--input_tumour_directory", str(input_dir),
        "--output_directory", str(tmp_path),
        "--debug",
        "--debug_solution_file", str(debug_solution),
        "--complexity", "100",
        *_PYOMO_GUROBI,
    )

    golden_dir = _golden(repo_root, "solution_provided")
    assert_csv_matches_golden(
        tmp_path / f"ALPACA_output_{TUMOUR_ID}.csv",
        golden_dir / f"ALPACA_output_{TUMOUR_ID}.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )


@pytest.mark.integration
@pytest.mark.requires_r
@pytest.mark.skipif(
    shutil.which("Rscript") is None,
    reason="Rscript not on PATH — skipping test that requires input-conversion",
)
def test_x_chromosome(tmp_path, repo_root, run_alpaca, update_golden):
    """Runs input-conversion (needs Rscript) then alpaca run on X-chromosome data."""
    input_dir = repo_root / "tests" / "x_chromosome" / "input" / TUMOUR_ID
    refphase_rdata = input_dir / f"{TUMOUR_ID}-refphase-results.RData"
    conipher_tree = input_dir / f"{TUMOUR_ID}.tree.RDS"

    run_alpaca(
        "input-conversion",
        "--tumour_id", TUMOUR_ID,
        "--refphase_rData", str(refphase_rdata),
        "--CONIPHER_tree_object", str(conipher_tree),
        "--output_dir", str(input_dir),
    )

    run_alpaca(
        "run",
        "--input_tumour_directory", str(input_dir),
        "--output_directory", str(tmp_path),
        "--debug",
        *_PYOMO_GLPK,
    )

    golden_dir = _golden(repo_root, "x_chromosome")
    assert_csv_matches_golden(
        tmp_path / f"ALPACA_output_{TUMOUR_ID}.csv",
        golden_dir / f"ALPACA_output_{TUMOUR_ID}.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )
    assert_csv_matches_golden(
        tmp_path / "cn_change_to_ancestor.csv",
        golden_dir / "cn_change_to_ancestor.csv",
        ignore_cols=VOLATILE_COLS,
        update=update_golden,
    )
