"""Tests for single-sample tumours using fully mocked input data.

Inputs are generated by ``mock_inputs`` into pytest's ``tmp_path``; no fixture
files are committed. The ground-truth clone copy numbers are known, so the
assertions check properties of the output rather than a golden file.
"""

import pandas as pd
import pytest

from alpaca.plotting import plot_cpn_per_clone, plot_heatmap_with_tree
from alpaca.plotting_helpers import get_chr_table
from alpaca.utils import read_tree_json

from mock_inputs import (
    CLONE_PROPORTIONS,
    SAMPLE,
    SEGMENT_TRUTH,
    SINGLE_CLONE_PROPORTIONS,
    SINGLE_CLONE_TREE_PATHS,
    SINGLE_CLONE_TRUTH,
    TREE_PATHS,
    TUMOUR_ID,
    make_mock_tumour_dir,
    observed_copy_numbers,
)

_PYOMO_SCIP = ("--solver", "pyomo", "--pyomo_solver", "scip", "--pyomo_solver_options", "seed=1 threads=1")


# ---------------------------------------------------------------------------
# Mock input sanity (fast, no solver)
# ---------------------------------------------------------------------------


def test_mock_proportions_sum_to_one():
    assert sum(CLONE_PROPORTIONS.values()) == pytest.approx(1.0)


def test_mock_tree_covers_all_clones():
    assert {c for path in TREE_PATHS for c in path} == set(CLONE_PROPORTIONS)
    for truth in SEGMENT_TRUTH.values():
        assert set(truth) == set(CLONE_PROPORTIONS)


def test_mock_directory_layout_single_sample(tmp_path):
    tumour_dir = make_mock_tumour_dir(tmp_path)
    for name in ("ALPACA_input_table.csv", "ci_table.csv", "cp_table.csv", "tree_paths.json"):
        assert (tumour_dir / name).exists(), name

    table = pd.read_csv(tumour_dir / "ALPACA_input_table.csv")
    assert table["sample"].unique().tolist() == [SAMPLE]
    assert set(table["segment"]) == set(SEGMENT_TRUTH)

    cp = pd.read_csv(tumour_dir / "cp_table.csv", index_col="clone")
    assert cp.columns.tolist() == [SAMPLE]
    assert cp[SAMPLE].sum() == pytest.approx(1.0)

    segment_files = sorted((tumour_dir / "segments").glob("*.csv"))
    assert len(segment_files) == len(SEGMENT_TRUTH)


def test_mock_observed_copy_numbers_match_truth(tmp_path):
    tumour_dir = make_mock_tumour_dir(tmp_path)
    table = pd.read_csv(tumour_dir / "ALPACA_input_table.csv").set_index("segment")
    for seg, truth in SEGMENT_TRUTH.items():
        exp_a, exp_b = observed_copy_numbers(truth, CLONE_PROPORTIONS)
        assert table.loc[seg, "cpnA"] == pytest.approx(exp_a)
        assert table.loc[seg, "cpnB"] == pytest.approx(exp_b)


# ---------------------------------------------------------------------------
# End-to-end runs
# ---------------------------------------------------------------------------


def _run(run_alpaca, tumour_dir, out_dir):
    run_alpaca(
        "run",
        "--input_tumour_directory", str(tumour_dir),
        "--output_directory", str(out_dir),
        "--debug",
        *_PYOMO_SCIP,
    )
    return pd.read_csv(out_dir / f"ALPACA_output_{TUMOUR_ID}.csv")


@pytest.mark.integration
def test_single_sample_single_segment(tmp_path, run_alpaca):
    """One tumour, one sample, one segment: the smallest possible case."""
    seg = "1_1000000_5000000"
    tumour_dir = make_mock_tumour_dir(tmp_path / "in", segments=[seg])
    out = tmp_path / "out"
    df = _run(run_alpaca, tumour_dir, out)

    assert set(df["segment"]) == {seg}
    assert set(df["tumour_id"]) == {TUMOUR_ID}
    assert set(df["clone"]) == set(CLONE_PROPORTIONS)
    assert len(df) == len(CLONE_PROPORTIONS)
    assert (df[["pred_CN_A", "pred_CN_B"]] >= 0).all().all()
    # integer copy-number predictions
    assert (df["pred_CN_A"] == df["pred_CN_A"].round()).all()
    assert (df["pred_CN_B"] == df["pred_CN_B"].round()).all()
    assert (out / "cn_change_to_ancestor.csv").exists()


@pytest.mark.integration
def test_single_sample_reconstruction_fits_observation(tmp_path, run_alpaca):
    """Predicted clone CNs, mixed by clone proportions, should be close to the observed CN."""
    seg = "1_1000000_5000000"
    tumour_dir = make_mock_tumour_dir(tmp_path / "in", segments=[seg])
    df = _run(run_alpaca, tumour_dir, tmp_path / "out").set_index("clone")

    obs_a, obs_b = observed_copy_numbers(SEGMENT_TRUTH[seg], CLONE_PROPORTIONS)
    rec_a = sum(CLONE_PROPORTIONS[c] * df.loc[c, "pred_CN_A"] for c in CLONE_PROPORTIONS)
    rec_b = sum(CLONE_PROPORTIONS[c] * df.loc[c, "pred_CN_B"] for c in CLONE_PROPORTIONS)
    # observation was built from integer truth, so reconstruction should stay within the CI
    assert abs(rec_a - obs_a) <= 0.2 + 1e-6
    assert abs(rec_b - obs_b) <= 0.2 + 1e-6


@pytest.mark.integration
def test_single_sample_multiple_segments(tmp_path, run_alpaca):
    """One sample across several segments produces one block of clone rows per segment."""
    tumour_dir = make_mock_tumour_dir(tmp_path / "in")
    df = _run(run_alpaca, tumour_dir, tmp_path / "out")

    assert set(df["segment"]) == set(SEGMENT_TRUTH)
    counts = df.groupby("segment")["clone"].nunique()
    assert (counts == len(CLONE_PROPORTIONS)).all()


@pytest.mark.integration
def test_single_sample_get_scores(tmp_path, run_alpaca):
    tumour_dir = make_mock_tumour_dir(tmp_path / "in", segments=["1_1000000_5000000"])
    out = tmp_path / "out"
    _run(run_alpaca, tumour_dir, out)
    run_alpaca(
        "get-scores",
        "--input_tumour_directory", str(tumour_dir),
        "--output_directory", str(out),
    )
    scores = pd.read_csv(out / f"ALPACA_scores_{TUMOUR_ID}.csv")
    assert {"tumour_id", "segment", "D_score", "CI_score"}.issubset(scores.columns)
    assert len(scores) == 1


# ---------------------------------------------------------------------------
# Single sample, single clone (monoclonal tumour)
# ---------------------------------------------------------------------------


def _single_clone_dir(root, segments=None):
    return make_mock_tumour_dir(
        root,
        segments=segments,
        tree_paths=SINGLE_CLONE_TREE_PATHS,
        proportions=SINGLE_CLONE_PROPORTIONS,
        truth=SINGLE_CLONE_TRUTH,
    )


def test_mock_single_clone_layout(tmp_path):
    tumour_dir = _single_clone_dir(tmp_path)
    cp = pd.read_csv(tumour_dir / "cp_table.csv", index_col="clone")
    assert cp.index.tolist() == ["clone1"]
    assert cp[SAMPLE].tolist() == [1.0]

    # a pure single-clone sample observes exactly the clone's copy number
    table = pd.read_csv(tumour_dir / "ALPACA_input_table.csv").set_index("segment")
    for seg, truth in SINGLE_CLONE_TRUTH.items():
        assert (table.loc[seg, "cpnA"], table.loc[seg, "cpnB"]) == truth["clone1"]


@pytest.mark.integration
def test_single_sample_single_clone_recovers_truth(tmp_path, run_alpaca):
    """With one clone and one sample the prediction must equal the observed integer CN."""
    seg = "1_1000000_5000000"
    tumour_dir = _single_clone_dir(tmp_path / "in", segments=[seg])
    out = tmp_path / "out"
    df = _run(run_alpaca, tumour_dir, out)

    assert df["clone"].tolist() == ["clone1"]
    assert set(df["segment"]) == {seg}
    row = df.iloc[0]
    assert (row["pred_CN_A"], row["pred_CN_B"]) == SINGLE_CLONE_TRUTH[seg]["clone1"]


@pytest.mark.integration
def test_single_sample_single_clone_multiple_segments(tmp_path, run_alpaca):
    tumour_dir = _single_clone_dir(tmp_path / "in")
    df = _run(run_alpaca, tumour_dir, tmp_path / "out").set_index("segment")

    assert set(df.index) == set(SINGLE_CLONE_TRUTH)
    for seg, truth in SINGLE_CLONE_TRUTH.items():
        assert (df.loc[seg, "pred_CN_A"], df.loc[seg, "pred_CN_B"]) == truth["clone1"]


# ---------------------------------------------------------------------------
# Plotting a single-clone tumour (regression: tree with no edges)
# ---------------------------------------------------------------------------


@pytest.fixture
def single_clone_plot_inputs(tmp_path):
    tumour_dir = _single_clone_dir(tmp_path / "in")
    chr_csv = tmp_path / "chr.csv"
    pd.DataFrame({"chr": ["chr1", "chr2"], "len": [10_000_000, 9_000_000]}).to_csv(chr_csv, index=False)
    alpaca_output = pd.DataFrame(
        {
            "clone": ["clone1"] * len(SINGLE_CLONE_TRUTH),
            "pred_CN_A": [truth["clone1"][0] for truth in SINGLE_CLONE_TRUTH.values()],
            "pred_CN_B": [truth["clone1"][1] for truth in SINGLE_CLONE_TRUTH.values()],
            "tumour_id": TUMOUR_ID,
            "segment": list(SINGLE_CLONE_TRUTH),
        }
    )
    return {
        "tree": read_tree_json(str(tumour_dir / "tree_paths.json")),
        "alpaca_output": alpaca_output,
        "cp_table": pd.read_csv(tumour_dir / "cp_table.csv").set_index("clone"),
        "chr_table": get_chr_table(chr_csv),
    }


@pytest.mark.parametrize("allele", ["A", "B"])
def test_plot_heatmap_with_tree_single_clone(single_clone_plot_inputs, allele):
    inputs = single_clone_plot_inputs
    fig = plot_heatmap_with_tree(
        tree=inputs["tree"],
        alpaca_output=inputs["alpaca_output"].copy(),
        cp_table=inputs["cp_table"],
        chr_table=inputs["chr_table"],
        allele=allele,
    )
    assert len(fig.data) > 0


def test_plot_cpn_per_clone_single_clone(single_clone_plot_inputs):
    inputs = single_clone_plot_inputs
    fig = plot_cpn_per_clone(
        tree=inputs["tree"],
        alpaca_output=inputs["alpaca_output"].copy(),
        cp_table=inputs["cp_table"],
        chr_table=inputs["chr_table"],
        max_cpn_cap=8,
    )
    assert len(fig.data) > 0
